### ISSUE TITLE
The challenge status was always "INVALID"

### ISSUE THREAD

**Issue by fsl1994** [shred/acme4j#135] opened 2023-04-20 14:14 UTC
Hello, I consulted you on gitlab last week, and I'm bothering you again. Hello, I consulted you on gitlab last week, and I'm bothering you again. I bought A domain name with A record configured. Then I tried to produce certificates. The challenge type was "HTTP", but the challenge status was always "INVALID", so the certificate could not be created. Can you help me see what the problem is.Looking forward to your reply. So the certificate could not be created. Can you help me to see what is wrong? Looking forward to your reply.

![image](https://user-images.githubusercontent.com/49866023/233391384-b769ff12-e130-4837-8683-352c45ac2924.png)

![image](https://user-images.githubusercontent.com/49866023/233391447-f0d56902-2169-41c7-9229-b2ecaef10de9.png)

**Comment by shred** [comment] 2023-04-20 16:24
The `Order` object also stores an error if it failed. Can you add a `getError()` to the log, e.g. like that?

```java
                if (order.getStatus() == Status.INVALID) {
                    LOG.error("Order has failed, reason: {}", order.getError());
                    LOG.error(order.getError().toString());
                    throw new AcmeException("Order failed... Giving up.");
                }
```

It should then log the reason why the order is invalid.

**Comment by fsl1994** [comment] 2023-04-21 04:11
I didn't throw any exceptions during the authorization process, and then after authoriz(auth) is done, this method [order.execute(csrb.getEncoded())] should have an exception. 
The exception message is: "Org. Shredzone. Acme4j. Exception. AcmeServerException: Order 's status (" invalid") is not acceptable for finalization"

![ilnW09ZAiK](https://user-images.githubusercontent.com/49866023/233538200-d9beec91-5c59-4ae7-b57e-f038e44fe001.jpg)
![7wJFk4J2im](https://user-images.githubusercontent.com/49866023/233538317-a0e20dfc-23f4-405f-b0af-b8a183d86af2.jpg)

**Comment by shred** [comment] 2023-04-21 04:50
OK, it wasn't clear to me that the challenge is failing. Please change your code in line 436-439 like this:

```java
if (status == Status.INVALID) {
    Debug.logInfo("authorize-domainName=%s, status=%s, Challenge failed... Giving up.", module, domain, status);
    Debug.logError("authorize-domainName=%s, reason=%s", module, domain, challenge.getError());
    throw new AcmeException("Challenge failed.. Giving up");
}
```

`challenge.getError()` will give you the reason for why your challenge has failed. That's in the example, too.

**Comment by fsl1994** [comment] 2023-04-21 05:16
I saw this challenge.getError :    "status=INVALID, error=2a02:4780:3:696:0:aae:4af9:1: Invalid response from http://almanostore.com/.well-known/acme-challenge/qjUxh0eAfFpFAUrkfc8g4yxzw_q5bg_vYcftlXlac7M: 404, Challenge failed... Giving up."

I might know what went wrong. but I didn't know why it didn't work. Was it because I configured ipv6?
![eyGgB0q6Vb](https://user-images.githubusercontent.com/49866023/233546490-029080da-106d-4c1e-b806-65e17c1e8ba5.jpg)

**Comment by shred** [comment] 2023-04-21 05:32
I don't think it's related to the IPv6 configuration.

The error means that Let's Encrypt has tried to access your HTTP challenge at http://almanostore.com/.well-known/acme-challenge/qjUxh0eAfFpFAUrkfc8g4yxzw_q5bg_vYcftlXlac7M, but got a 404 from your web server instead of the challenge response.

You should check that the response file is reachable from public. Is your web server configured properly to deliver the file? Also it must be available there _before_ you invoke `challenge.trigger()`, and it must be there until the challenge is completed (either in `VALID` or `INVALID` state).

**Comment by fsl1994** [comment] 2023-04-21 05:38
However, my other test domain name is able to generate the certificate correctly, and path is accessible to the public network

**Comment by fsl1994** [comment] 2023-04-21 05:38
I access this path on the Internet and can download the file.   http://almanostore.com/.well-known/acme-challenge/qjUxh0eAfFpFAUrkfc8g4yxzw_q5bg_vYcftlXlac7M

**Comment by shred** [comment] 2023-04-21 05:46
Well, all I can tell you is that Let's Encrypt couldn't download the file, but got a 404.

A common problem is that `challenge.trigger()` is invoked too early. Let's Encrypt may access the file as soon as `challenge.trigger()` is invoked. If your web server is not ready yet (e.g. because the file has not been written yet, or needs to be replicated first), you will get this error.

**Comment by fsl1994** [comment] 2023-04-21 05:53
oh， can I make the thread wait a few seconds before calling challenge.trigger() ？Maybe can solve this problem？

**Comment by shred** [comment] 2023-04-21 05:54
It depends on your implementation. But it's surely worth a try.

**Comment by fsl1994** [comment] 2023-04-21 06:04
I forgot to show you the code for the challenge. I wrote this file after the findChallenge() method. It should be okay, right?

![Uploading HODJNf7H0O.jpg…]()

**Comment by fsl1994** [comment] 2023-04-21 06:04
I forgot to show you the code for the challenge. I wrote this file after the findChallenge() method. It should be okay, right?

![Uploading HODJNf7H0O.jpg…]()

**Comment by shred** [comment] 2023-04-21 06:13
Generally it looks good to me.

On a side node: Your `bufferedWriter` is not closed. This is not the cause for the problem because you do a `bufferedWriter.flush()`. However you should prefer constructs like `try (BufferedWriter bufferedWriter = new BufferedWriter(new FileWriter(file))) { ... }`, because it will auto-close your writer at the end of the try block. Also see here: https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html

**Comment by fsl1994** [comment] 2023-04-21 06:54
I'm sorry. I'm a little bad at it. Where should I call this method [challenge.trigger() ], and how should I change it? Can you teach me? hahaha

![gcMY5Wm1y0](https://user-images.githubusercontent.com/49866023/233562868-b5e7ea68-04f1-4d71-af4a-370e174dc2ee.jpg)

**Comment by shred** [comment] 2023-04-21 11:03
What you can try out is a `Thread.sleep(3000L)` before `challenge.trigger()`. Anyway, the reason for the error is that Let's Encrypt was unable to access your challenge file. The problem is related with your server setup or your implementation, and is out of scope of this issue. Please understand that I don't have the time to debug that problem for you, but you should find everything you need in this issue.

I will close this ticket now, since the problem is not related to acme4j.

**Closed by shred** 2023-04-21 11:03 UTC
